# 工作流名称
name: Assemble Android Debug

# 触发工作流程的事件
on:
  push:
    tags: [ v*, r*, a* ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

# 工作流环境变量
env:
  # 应用的application_id
  APP_ID: ${{secrets.APP_ID}}
  # 应用名称
  APP_NAME: Taro
  # 打包类型
  BUILD_TYPE: debug
  # 版本名称
  VERSION_NAME: 1.11.0
  # 版本号
  VERSION_CODE: 111000
  # 密钥库文件
  KEYSTORE_FILE: debug.keystore
  # 密钥库口令
  KEYSTORE_PASSWORD: ${{secrets.DEBUG_KEYSTORE_PASSWORD}}
  # 密钥库别名
  KEYSTORE_KEY_ALIAS: android
  # 密钥库别名口令
  KEYSTORE_KEY_PASSWORD: ${{secrets.DEBUG_KEYSTORE_PASSWORD}}

# 工作流作业
jobs:
  assemble:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Cache Gradle
        uses: actions/cache@v2
        env:
          cache-name: gradle-cache
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle
          restore-keys: |
            ${{ runner.os }}-gradle
      - name: Assemble Android ${{ env.BUILD_TYPE }}
        run: |
          sudo apt install -y ruby-bundler
          cd android
          bundle update
          bundle exec fastlane assemble
        env:
          KEYSTORE_FILE: ${{ github.workspace }}/android/app/${{ env.KEYSTORE_FILE }}
      - name: Upload Android Products
        uses: actions/upload-artifact@v2
        with:
          name: app-${{ env.BUILD_TYPE }}
          path: ${{ github.workspace }}/android/app/build/outputs/apk/${{ env.BUILD_TYPE }}/app-${{ env.BUILD_TYPE }}.apk
      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: ${{ contains(github.ref, 'beta') }}
          files: |
            android/app/build/outputs/apk/${{ env.BUILD_TYPE }}/app-${{ env.BUILD_TYPE }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
